import type { Locale } from "@/lib/i18n/config";

/**
 * Localized report TEMPLATE strings — headings, field labels, the readiness
 * breakdown labels, the disclaimer and footer. These are deterministic and
 * safe to translate. The AI-generated analysis (reasoning prose, key factors,
 * questions, explanation) stays in the language the classifier produced it in
 * (English); `analysisNote` tells the reader so, and is shown only for
 * non-English reports.
 */
export interface ReportMessages {
  title: string;
  classificationId: string;
  generated: string;
  analysisNote: string;
  product: string;
  name: string;
  description: string;
  material: string;
  intendedUse: string;
  tradeLane: string;
  declaredValue: string;
  hsCodeCandidates: string;
  recommendedCandidate: string;
  code: string;
  codeTitle: string;
  confidence: string;
  humanReviewRequired: string;
  yes: string;
  no: string;
  reviewReason: string;
  alternativeCandidates: string;
  reasoning: string;
  keyFactors: string;
  dutyTaxEstimate: string;
  reference: string;
  dutyRate: string;
  vatTax: string;
  estimatedDuty: string;
  requiredDocuments: string;
  riskFlags: string;
  missingInformation: string;
  explanation: string;
  readinessScore: string;
  strong: string;
  needsAttention: string;
  suggestedNextActions: string;
  confidenceLabels: { low: string; medium: string; high: string };
  disclaimer: string;
  footer: string;
}

const en: ReportMessages = {
  title: "Kustaro Customs-Readiness Report",
  classificationId: "Classification ID",
  generated: "Generated",
  analysisNote: "",
  product: "Product",
  name: "Name",
  description: "Description",
  material: "Material",
  intendedUse: "Intended use",
  tradeLane: "Trade lane",
  declaredValue: "Declared value",
  hsCodeCandidates: "HS-Code Candidates",
  recommendedCandidate: "Recommended candidate",
  code: "Code",
  codeTitle: "Title",
  confidence: "Confidence",
  humanReviewRequired: "Human review required",
  yes: "YES",
  no: "No",
  reviewReason: "Review reason",
  alternativeCandidates: "Alternative candidates",
  reasoning: "Reasoning",
  keyFactors: "Key factors",
  dutyTaxEstimate: "Duty / tax estimate",
  reference: "reference",
  dutyRate: "Duty rate",
  vatTax: "VAT/tax",
  estimatedDuty: "Estimated duty",
  requiredDocuments: "Required documents",
  riskFlags: "Risk flags",
  missingInformation: "Missing information",
  explanation: "Explanation for customs review",
  readinessScore: "Customs-readiness score",
  strong: "Strong",
  needsAttention: "Needs attention",
  suggestedNextActions: "Suggested next actions",
  confidenceLabels: { low: "low", medium: "medium", high: "high" },
  disclaimer:
    "This report is a customs-readiness recommendation generated from available product information and tariff-reference data. It is not legal advice and does not guarantee acceptance by customs authorities. Final classification and customs declarations should be verified before official use.",
  footer: "Generated by Kustaro — customs-readiness recommendations for review.",
};

const tr: ReportMessages = {
  title: "Kustaro Gümrük Hazırlık Raporu",
  classificationId: "Sınıflandırma No",
  generated: "Oluşturulma",
  analysisNote:
    "Aşağıdaki yazılı analiz İngilizce (asıl dil) olarak sunulmuştur; bölüm başlıkları ve etiketler çevrilmiştir.",
  product: "Ürün",
  name: "Ad",
  description: "Açıklama",
  material: "Malzeme",
  intendedUse: "Kullanım amacı",
  tradeLane: "Ticaret hattı",
  declaredValue: "Beyan değeri",
  hsCodeCandidates: "HS Kodu Adayları",
  recommendedCandidate: "Önerilen aday",
  code: "Kod",
  codeTitle: "Tanım",
  confidence: "Güven",
  humanReviewRequired: "İnceleme gerekli",
  yes: "EVET",
  no: "Hayır",
  reviewReason: "İnceleme nedeni",
  alternativeCandidates: "Alternatif adaylar",
  reasoning: "Gerekçe",
  keyFactors: "Temel faktörler",
  dutyTaxEstimate: "Gümrük vergisi / vergi tahmini",
  reference: "referans",
  dutyRate: "Vergi oranı",
  vatTax: "KDV/vergi",
  estimatedDuty: "Tahmini vergi",
  requiredDocuments: "Gerekli belgeler",
  riskFlags: "Risk işaretleri",
  missingInformation: "Eksik bilgiler",
  explanation: "Gümrük incelemesi açıklaması",
  readinessScore: "Gümrük hazırlık puanı",
  strong: "Güçlü yönler",
  needsAttention: "Dikkat gerektirenler",
  suggestedNextActions: "Önerilen sonraki adımlar",
  confidenceLabels: { low: "düşük", medium: "orta", high: "yüksek" },
  disclaimer:
    "Bu rapor, mevcut ürün bilgileri ve tarife referans verilerinden üretilen bir gümrük hazırlık önerisidir. Hukuki tavsiye değildir ve gümrük idarelerince kabul garantisi vermez. Nihai sınıflandırma ve gümrük beyanları resmî kullanım öncesinde doğrulanmalıdır.",
  footer:
    "Kustaro tarafından oluşturulmuştur — inceleme amaçlı gümrük hazırlık önerileri.",
};

const es: ReportMessages = {
  title: "Informe de Preparación Aduanera de Kustaro",
  classificationId: "ID de clasificación",
  generated: "Generado",
  analysisNote:
    "El análisis escrito a continuación se ofrece en inglés (idioma autorizado); los títulos de sección y las etiquetas están traducidos.",
  product: "Producto",
  name: "Nombre",
  description: "Descripción",
  material: "Material",
  intendedUse: "Uso previsto",
  tradeLane: "Ruta comercial",
  declaredValue: "Valor declarado",
  hsCodeCandidates: "Candidatos de código HS",
  recommendedCandidate: "Candidato recomendado",
  code: "Código",
  codeTitle: "Título",
  confidence: "Confianza",
  humanReviewRequired: "Requiere revisión",
  yes: "SÍ",
  no: "No",
  reviewReason: "Motivo de revisión",
  alternativeCandidates: "Candidatos alternativos",
  reasoning: "Razonamiento",
  keyFactors: "Factores clave",
  dutyTaxEstimate: "Estimación de aranceles / impuestos",
  reference: "referencia",
  dutyRate: "Tasa arancelaria",
  vatTax: "IVA/impuesto",
  estimatedDuty: "Arancel estimado",
  requiredDocuments: "Documentos requeridos",
  riskFlags: "Alertas de riesgo",
  missingInformation: "Información faltante",
  explanation: "Explicación para la revisión aduanera",
  readinessScore: "Puntuación de preparación aduanera",
  strong: "Puntos fuertes",
  needsAttention: "Requiere atención",
  suggestedNextActions: "Próximas acciones sugeridas",
  confidenceLabels: { low: "baja", medium: "media", high: "alta" },
  disclaimer:
    "Este informe es una recomendación de preparación aduanera generada a partir de la información disponible del producto y datos de referencia arancelaria. No es asesoría legal ni garantiza la aceptación por las autoridades aduaneras. La clasificación final y las declaraciones deben verificarse antes de su uso oficial.",
  footer:
    "Generado por Kustaro — recomendaciones de preparación aduanera para revisión.",
};

const fr: ReportMessages = {
  title: "Rapport de préparation douanière Kustaro",
  classificationId: "ID de classification",
  generated: "Généré",
  analysisNote:
    "L'analyse rédigée ci-dessous est fournie en anglais (langue faisant foi) ; les titres de section et les libellés sont traduits.",
  product: "Produit",
  name: "Nom",
  description: "Description",
  material: "Matière",
  intendedUse: "Usage prévu",
  tradeLane: "Route commerciale",
  declaredValue: "Valeur déclarée",
  hsCodeCandidates: "Candidats de code SH",
  recommendedCandidate: "Candidat recommandé",
  code: "Code",
  codeTitle: "Intitulé",
  confidence: "Confiance",
  humanReviewRequired: "Revue requise",
  yes: "OUI",
  no: "Non",
  reviewReason: "Motif de revue",
  alternativeCandidates: "Candidats alternatifs",
  reasoning: "Raisonnement",
  keyFactors: "Facteurs clés",
  dutyTaxEstimate: "Estimation des droits / taxes",
  reference: "référence",
  dutyRate: "Taux de droit",
  vatTax: "TVA/taxe",
  estimatedDuty: "Droits estimés",
  requiredDocuments: "Documents requis",
  riskFlags: "Alertes de risque",
  missingInformation: "Informations manquantes",
  explanation: "Explication pour la revue douanière",
  readinessScore: "Score de préparation douanière",
  strong: "Points forts",
  needsAttention: "À surveiller",
  suggestedNextActions: "Prochaines actions suggérées",
  confidenceLabels: { low: "faible", medium: "moyenne", high: "élevée" },
  disclaimer:
    "Ce rapport est une recommandation de préparation douanière générée à partir des informations produit disponibles et de données tarifaires de référence. Il ne constitue pas un avis juridique et ne garantit pas l'acceptation par les autorités douanières. La classification finale et les déclarations doivent être vérifiées avant tout usage officiel.",
  footer:
    "Généré par Kustaro — recommandations de préparation douanière pour revue.",
};

const de: ReportMessages = {
  title: "Kustaro Zollbereitschafts-Bericht",
  classificationId: "Klassifizierungs-ID",
  generated: "Erstellt",
  analysisNote:
    "Die schriftliche Analyse unten wird auf Englisch (maßgebliche Sprache) bereitgestellt; Abschnittsüberschriften und Bezeichnungen sind übersetzt.",
  product: "Produkt",
  name: "Name",
  description: "Beschreibung",
  material: "Material",
  intendedUse: "Verwendungszweck",
  tradeLane: "Handelsroute",
  declaredValue: "Deklarierter Wert",
  hsCodeCandidates: "HS-Code-Kandidaten",
  recommendedCandidate: "Empfohlener Kandidat",
  code: "Code",
  codeTitle: "Bezeichnung",
  confidence: "Konfidenz",
  humanReviewRequired: "Prüfung erforderlich",
  yes: "JA",
  no: "Nein",
  reviewReason: "Prüfgrund",
  alternativeCandidates: "Alternative Kandidaten",
  reasoning: "Begründung",
  keyFactors: "Schlüsselfaktoren",
  dutyTaxEstimate: "Zoll- / Steuerschätzung",
  reference: "Referenz",
  dutyRate: "Zollsatz",
  vatTax: "MwSt./Steuer",
  estimatedDuty: "Geschätzter Zoll",
  requiredDocuments: "Erforderliche Dokumente",
  riskFlags: "Risikohinweise",
  missingInformation: "Fehlende Angaben",
  explanation: "Erläuterung für die Zollprüfung",
  readinessScore: "Zollbereitschafts-Score",
  strong: "Stark",
  needsAttention: "Zu beachten",
  suggestedNextActions: "Vorgeschlagene nächste Schritte",
  confidenceLabels: { low: "niedrig", medium: "mittel", high: "hoch" },
  disclaimer:
    "Dieser Bericht ist eine Zollbereitschafts-Empfehlung, die aus verfügbaren Produktinformationen und Tarif-Referenzdaten erstellt wurde. Er ist keine Rechtsberatung und garantiert keine Anerkennung durch Zollbehörden. Endgültige Klassifizierung und Zollanmeldungen sind vor amtlicher Verwendung zu prüfen.",
  footer:
    "Erstellt von Kustaro — Zollbereitschafts-Empfehlungen zur Prüfung.",
};

const zh: ReportMessages = {
  title: "Kustaro 清关就绪报告",
  classificationId: "归类编号",
  generated: "生成时间",
  analysisNote:
    "以下书面分析以英文（具有约束力的语言）提供；章节标题与字段标签已翻译。",
  product: "产品",
  name: "名称",
  description: "描述",
  material: "材质",
  intendedUse: "预期用途",
  tradeLane: "贸易航线",
  declaredValue: "申报价值",
  hsCodeCandidates: "HS 编码候选",
  recommendedCandidate: "推荐候选",
  code: "编码",
  codeTitle: "品名",
  confidence: "置信度",
  humanReviewRequired: "需人工复核",
  yes: "是",
  no: "否",
  reviewReason: "复核原因",
  alternativeCandidates: "备选候选",
  reasoning: "推理",
  keyFactors: "关键因素",
  dutyTaxEstimate: "关税 / 税费估算",
  reference: "参考",
  dutyRate: "税率",
  vatTax: "增值税/税费",
  estimatedDuty: "预计关税",
  requiredDocuments: "所需单证",
  riskFlags: "风险提示",
  missingInformation: "缺失信息",
  explanation: "供海关复核的说明",
  readinessScore: "清关就绪评分",
  strong: "优势",
  needsAttention: "需注意",
  suggestedNextActions: "建议的后续行动",
  confidenceLabels: { low: "低", medium: "中", high: "高" },
  disclaimer:
    "本报告是基于现有产品信息和关税参考数据生成的清关就绪建议，不构成法律意见，也不保证海关当局的认可。正式使用前，请核实最终归类和报关内容。",
  footer: "由 Kustaro 生成 —— 供复核的清关就绪建议。",
};

const ar: ReportMessages = {
  title: "تقرير الجاهزية الجمركية من Kustaro",
  classificationId: "رقم التصنيف",
  generated: "تاريخ الإنشاء",
  analysisNote:
    "التحليل المكتوب أدناه مقدَّم بالإنجليزية (اللغة المُلزمة)؛ عناوين الأقسام والتسميات مترجمة.",
  product: "المنتج",
  name: "الاسم",
  description: "الوصف",
  material: "المادة",
  intendedUse: "الاستخدام المقصود",
  tradeLane: "مسار التجارة",
  declaredValue: "القيمة المصرّح بها",
  hsCodeCandidates: "مرشّحات رمز HS",
  recommendedCandidate: "المرشّح الموصى به",
  code: "الرمز",
  codeTitle: "الوصف",
  confidence: "الثقة",
  humanReviewRequired: "مراجعة مطلوبة",
  yes: "نعم",
  no: "لا",
  reviewReason: "سبب المراجعة",
  alternativeCandidates: "مرشّحات بديلة",
  reasoning: "التعليل",
  keyFactors: "العوامل الرئيسية",
  dutyTaxEstimate: "تقدير الرسوم / الضرائب",
  reference: "مرجعي",
  dutyRate: "معدل الرسوم",
  vatTax: "ضريبة القيمة المضافة/الضريبة",
  estimatedDuty: "الرسوم المقدّرة",
  requiredDocuments: "المستندات المطلوبة",
  riskFlags: "تنبيهات المخاطر",
  missingInformation: "المعلومات الناقصة",
  explanation: "شرح لمراجعة الجمارك",
  readinessScore: "درجة الجاهزية الجمركية",
  strong: "نقاط القوة",
  needsAttention: "بحاجة إلى انتباه",
  suggestedNextActions: "الإجراءات التالية المقترحة",
  confidenceLabels: { low: "منخفضة", medium: "متوسطة", high: "عالية" },
  disclaimer:
    "هذا التقرير توصية جاهزية جمركية مولّدة من معلومات المنتج المتاحة وبيانات التعرفة المرجعية. ليست استشارة قانونية ولا تضمن قبول السلطات الجمركية. يجب التحقق من التصنيف النهائي والتصاريح الجمركية قبل الاستخدام الرسمي.",
  footer: "أُنشئ بواسطة Kustaro — توصيات جاهزية جمركية للمراجعة.",
};

const pt: ReportMessages = {
  title: "Relatório de Prontidão Aduaneira da Kustaro",
  classificationId: "ID de classificação",
  generated: "Gerado",
  analysisNote:
    "A análise escrita abaixo é fornecida em inglês (idioma que prevalece); os títulos das seções e os rótulos estão traduzidos.",
  product: "Produto",
  name: "Nome",
  description: "Descrição",
  material: "Material",
  intendedUse: "Uso pretendido",
  tradeLane: "Rota comercial",
  declaredValue: "Valor declarado",
  hsCodeCandidates: "Candidatos de código SH",
  recommendedCandidate: "Candidato recomendado",
  code: "Código",
  codeTitle: "Descrição",
  confidence: "Confiança",
  humanReviewRequired: "Revisão necessária",
  yes: "SIM",
  no: "Não",
  reviewReason: "Motivo da revisão",
  alternativeCandidates: "Candidatos alternativos",
  reasoning: "Raciocínio",
  keyFactors: "Fatores principais",
  dutyTaxEstimate: "Estimativa de impostos / tributos",
  reference: "referência",
  dutyRate: "Alíquota",
  vatTax: "IVA/imposto",
  estimatedDuty: "Imposto estimado",
  requiredDocuments: "Documentos exigidos",
  riskFlags: "Alertas de risco",
  missingInformation: "Informações faltantes",
  explanation: "Explicação para a revisão aduaneira",
  readinessScore: "Pontuação de prontidão aduaneira",
  strong: "Pontos fortes",
  needsAttention: "Requer atenção",
  suggestedNextActions: "Próximas ações sugeridas",
  confidenceLabels: { low: "baixa", medium: "média", high: "alta" },
  disclaimer:
    "Este relatório é uma recomendação de prontidão aduaneira gerada a partir das informações disponíveis do produto e de dados tarifários de referência. Não é aconselhamento jurídico e não garante aceitação pelas autoridades aduaneiras. A classificação final e as declarações devem ser verificadas antes do uso oficial.",
  footer:
    "Gerado pela Kustaro — recomendações de prontidão aduaneira para revisão.",
};

export const REPORT_MESSAGES: Record<Locale, ReportMessages> = {
  en, tr, es, fr, de, zh, ar, pt,
};
