import type { TariffCode } from "@/types";

/**
 * Local seed tariff-code database (HS6-style codes, harmonized globally).
 *
 * This is the canonical reference dataset for the MVP. It is intentionally
 * code-resident (not DB-resident) so the classification engine works with zero
 * external dependencies. A matching SQL seed for the `tariff_codes` table is
 * generated from this same array via `scripts/generate-seed-sql.ts`.
 *
 * Duty rates are PLACEHOLDERS. Real measures require an official tariff adapter.
 */
export const SEED_TARIFF_CODES: TariffCode[] = [
  // ---------------------------------------------------------------- Apparel
  {
    code: "6109.10",
    jurisdiction: "GLOBAL",
    title: "T-shirts, singlets and other vests, of cotton, knitted",
    description:
      "Knitted or crocheted cotton t-shirts, singlets and vests for men, women or children.",
    keywords: ["t-shirt", "tee", "cotton", "knitted", "singlet", "vest", "apparel", "short sleeve", "shirt"],
    chapter: "61",
    section: "XI",
    dutyRatePlaceholder: "~12% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low",
  },
  {
    code: "6109.90",
    jurisdiction: "GLOBAL",
    title: "T-shirts and vests of other textile materials, knitted",
    description:
      "Knitted t-shirts, singlets and vests of textile materials other than cotton (e.g. synthetic blends).",
    keywords: ["t-shirt", "tee", "polyester", "synthetic", "blend", "knitted", "apparel", "vest"],
    chapter: "61",
    section: "XI",
    dutyRatePlaceholder: "~12% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low",
  },
  {
    code: "6110.20",
    jurisdiction: "GLOBAL",
    title: "Jerseys, pullovers, sweatshirts, of cotton, knitted",
    description:
      "Knitted cotton jerseys, pullovers, cardigans, sweatshirts and similar articles.",
    keywords: ["sweater", "jumper", "pullover", "sweatshirt", "hoodie", "cardigan", "cotton", "knitted"],
    chapter: "61",
    section: "XI",
    dutyRatePlaceholder: "~12% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low",
  },
  {
    code: "6203.42",
    jurisdiction: "GLOBAL",
    title: "Men's trousers and shorts, of cotton, not knitted",
    description:
      "Men's or boys' woven cotton trousers, bib and brace overalls, breeches and shorts.",
    keywords: ["trousers", "pants", "shorts", "chinos", "jeans", "cotton", "woven", "menswear"],
    chapter: "62",
    section: "XI",
    dutyRatePlaceholder: "~12% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low",
  },
  {
    code: "6204.62",
    jurisdiction: "GLOBAL",
    title: "Women's trousers and shorts, of cotton, not knitted",
    description:
      "Women's or girls' woven cotton trousers, bib and brace overalls, breeches and shorts.",
    keywords: ["trousers", "pants", "shorts", "cotton", "woven", "womenswear", "ladies"],
    chapter: "62",
    section: "XI",
    dutyRatePlaceholder: "~12% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low",
  },
  {
    code: "6205.20",
    jurisdiction: "GLOBAL",
    title: "Men's shirts, of cotton, not knitted",
    description: "Men's or boys' woven cotton shirts (dress and casual).",
    keywords: ["shirt", "dress shirt", "button", "cotton", "woven", "menswear", "formal"],
    chapter: "62",
    section: "XI",
    dutyRatePlaceholder: "~12% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low",
  },

  // --------------------------------------------------------------- Textiles
  {
    code: "5208.52",
    jurisdiction: "GLOBAL",
    title: "Woven cotton fabrics, printed, plain weave",
    description: "Printed plain-weave woven fabrics of cotton, ≥85% cotton by weight.",
    keywords: ["fabric", "cotton", "woven", "textile", "printed", "cloth", "material", "roll"],
    chapter: "52",
    section: "XI",
    dutyRatePlaceholder: "~8% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low",
  },
  {
    code: "6302.21",
    jurisdiction: "GLOBAL",
    title: "Bed linen, printed, of cotton, not knitted",
    description: "Printed cotton bed linen (sheets, pillowcases, duvet covers).",
    keywords: ["bed linen", "bedsheet", "pillowcase", "duvet", "cotton", "home textile", "linen"],
    chapter: "63",
    section: "XI",
    dutyRatePlaceholder: "~12% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low",
  },
  {
    code: "5703.20",
    jurisdiction: "GLOBAL",
    title: "Carpets and textile floor coverings, tufted, of nylon",
    description: "Tufted carpets and other tufted textile floor coverings of nylon or polyamide.",
    keywords: ["carpet", "rug", "floor covering", "tufted", "nylon", "textile", "mat"],
    chapter: "57",
    section: "XI",
    dutyRatePlaceholder: "~8% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low",
  },

  // -------------------------------------------------------------- Footwear
  {
    code: "6403.99",
    jurisdiction: "GLOBAL",
    title: "Footwear with leather uppers, not covering the ankle",
    description: "Footwear with outer soles of rubber/plastics and uppers of leather, low-cut.",
    keywords: ["shoes", "footwear", "leather", "sneakers", "loafers", "boots", "uppers"],
    chapter: "64",
    section: "XII",
    dutyRatePlaceholder: "~8% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low",
  },
  {
    code: "6402.99",
    jurisdiction: "GLOBAL",
    title: "Footwear with rubber or plastic uppers and soles",
    description: "Other footwear with outer soles and uppers of rubber or plastics, low-cut.",
    keywords: ["shoes", "footwear", "rubber", "plastic", "sandals", "flip flops", "sneakers"],
    chapter: "64",
    section: "XII",
    dutyRatePlaceholder: "~17% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low",
  },

  // ----------------------------------------------------------- Leather goods
  {
    code: "4202.21",
    jurisdiction: "GLOBAL",
    title: "Handbags with outer surface of leather",
    description: "Handbags, with or without shoulder strap, with outer surface of leather or composition leather.",
    keywords: ["handbag", "purse", "bag", "leather", "tote", "satchel", "accessory"],
    chapter: "42",
    section: "VIII",
    dutyRatePlaceholder: "~3% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low",
  },
  {
    code: "4202.92",
    jurisdiction: "GLOBAL",
    title: "Travel/sports bags with outer surface of textile or plastic",
    description: "Trunks, suitcases, backpacks and sports bags with outer surface of plastic sheeting or textiles.",
    keywords: ["backpack", "suitcase", "luggage", "travel bag", "sports bag", "rucksack", "case"],
    chapter: "42",
    section: "VIII",
    dutyRatePlaceholder: "~3.7% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [],
    riskLevel: "low",
  },
  {
    code: "4203.10",
    jurisdiction: "GLOBAL",
    title: "Articles of apparel of leather",
    description: "Articles of apparel (e.g. jackets) of leather or composition leather.",
    keywords: ["leather jacket", "leather apparel", "leather coat", "leather clothing"],
    chapter: "42",
    section: "VIII",
    dutyRatePlaceholder: "~4% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: ["May require CITES documentation if exotic leather is used."],
    riskLevel: "medium",
  },

  // ------------------------------------------------------------ Electronics
  {
    code: "8517.13",
    jurisdiction: "GLOBAL",
    title: "Smartphones",
    description: "Telephones for cellular networks (smartphones) and other wireless networks.",
    keywords: ["smartphone", "mobile phone", "cell phone", "iphone", "android phone", "handset"],
    chapter: "85",
    section: "XVI",
    dutyRatePlaceholder: "0% (ITA, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "declaration of conformity"],
    restrictionNotes: [
      "Contains radio modules — RED/FCC/CE conformity applies.",
      "Typically contains a lithium-ion battery — transport rules apply.",
    ],
    riskLevel: "medium",
  },
  {
    code: "8471.30",
    jurisdiction: "GLOBAL",
    title: "Portable computers (laptops, tablets) ≤10kg",
    description: "Portable automatic data-processing machines weighing not more than 10kg.",
    keywords: ["laptop", "notebook", "tablet", "computer", "ultrabook", "macbook"],
    chapter: "84",
    section: "XVI",
    dutyRatePlaceholder: "0% (ITA, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "declaration of conformity"],
    restrictionNotes: ["Typically contains a lithium-ion battery — transport rules apply."],
    riskLevel: "medium",
  },
  {
    code: "8518.30",
    jurisdiction: "GLOBAL",
    title: "Headphones and earphones",
    description: "Headphones and earphones, whether or not combined with a microphone.",
    keywords: ["headphones", "earphones", "earbuds", "headset", "audio", "wireless earbuds"],
    chapter: "85",
    section: "XVI",
    dutyRatePlaceholder: "~2% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "declaration of conformity"],
    restrictionNotes: ["Wireless models contain radio modules — RED/FCC/CE conformity applies."],
    riskLevel: "medium",
  },
  {
    code: "8528.72",
    jurisdiction: "GLOBAL",
    title: "Television reception apparatus, colour",
    description: "Reception apparatus for television, colour, whether or not incorporating radio/monitors.",
    keywords: ["television", "tv", "smart tv", "monitor", "display", "screen"],
    chapter: "85",
    section: "XVI",
    dutyRatePlaceholder: "~14% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "declaration of conformity"],
    restrictionNotes: ["Energy labelling and WEEE obligations may apply in the EU/UK."],
    riskLevel: "medium",
  },
  {
    code: "8544.42",
    jurisdiction: "GLOBAL",
    title: "Electric cables/connectors for ≤1000V, fitted with connectors",
    description: "Insulated electric conductors for a voltage ≤1000V, fitted with connectors (e.g. USB/charging cables).",
    keywords: ["cable", "usb cable", "charging cable", "connector", "wire", "cord", "lead"],
    chapter: "85",
    section: "XVI",
    dutyRatePlaceholder: "~3.3% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: [],
    riskLevel: "low",
  },
  {
    code: "9504.50",
    jurisdiction: "GLOBAL",
    title: "Video game consoles and machines",
    description: "Video game consoles and machines, other than those operated by coins/tokens.",
    keywords: ["game console", "gaming", "console", "playstation", "xbox", "nintendo"],
    chapter: "95",
    section: "XX",
    dutyRatePlaceholder: "0% (ITA, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "declaration of conformity"],
    restrictionNotes: ["Wireless controllers contain radio modules — conformity applies."],
    riskLevel: "medium",
  },

  // -------------------------------------------------------------- Batteries
  {
    code: "8507.60",
    jurisdiction: "GLOBAL",
    title: "Lithium-ion accumulators (batteries)",
    description: "Lithium-ion electric accumulators / rechargeable battery packs and cells.",
    keywords: ["battery", "lithium", "li-ion", "lithium-ion", "battery pack", "rechargeable", "cell", "accumulator", "e-bike battery", "power bank"],
    chapter: "85",
    section: "XVI",
    dutyRatePlaceholder: "~2.7% (EU MFN, placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "UN38.3 test summary",
      "safety data sheet (SDS)",
      "dangerous goods declaration",
    ],
    restrictionNotes: [
      "Class 9 dangerous goods (UN3480/UN3481) — IATA/IMDG/ADR transport rules apply.",
      "UN38.3 testing required for transport.",
      "EU Battery Regulation labelling/registration obligations may apply.",
    ],
    riskLevel: "high",
  },
  {
    code: "8506.50",
    jurisdiction: "GLOBAL",
    title: "Lithium primary cells and batteries (non-rechargeable)",
    description: "Primary (non-rechargeable) lithium cells and batteries.",
    keywords: ["battery", "lithium", "primary cell", "coin cell", "cr2032", "non-rechargeable"],
    chapter: "85",
    section: "XVI",
    dutyRatePlaceholder: "~4.7% (EU MFN, placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "UN38.3 test summary",
      "safety data sheet (SDS)",
    ],
    restrictionNotes: [
      "Class 9 dangerous goods (UN3090/UN3091) — transport rules apply.",
      "UN38.3 testing required for transport.",
    ],
    riskLevel: "high",
  },

  // -------------------------------------------------------------- Cosmetics
  {
    code: "3304.99",
    jurisdiction: "GLOBAL",
    title: "Beauty/skin-care preparations (other)",
    description: "Beauty or make-up preparations and skin-care preparations (other than medicaments).",
    keywords: ["cosmetic", "skincare", "cream", "lotion", "serum", "moisturizer", "makeup", "beauty"],
    chapter: "33",
    section: "VI",
    dutyRatePlaceholder: "0% (EU MFN, placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "ingredient/INCI list",
      "cosmetic product safety report",
    ],
    restrictionNotes: [
      "EU Cosmetics Regulation 1223/2009 — CPNP notification and Responsible Person required.",
      "UK requires SCPN notification post-Brexit.",
    ],
    riskLevel: "high",
  },
  {
    code: "3303.00",
    jurisdiction: "GLOBAL",
    title: "Perfumes and toilet waters",
    description: "Perfumes and eau de toilette preparations.",
    keywords: ["perfume", "fragrance", "eau de toilette", "cologne", "scent", "aftershave"],
    chapter: "33",
    section: "VI",
    dutyRatePlaceholder: "0% (EU MFN, placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "ingredient/INCI list",
      "safety data sheet (SDS)",
    ],
    restrictionNotes: [
      "Alcohol-based — may be flammable (Class 3 dangerous goods) for transport.",
      "EU/UK cosmetic notification required.",
    ],
    riskLevel: "high",
  },
  {
    code: "3305.10",
    jurisdiction: "GLOBAL",
    title: "Shampoos",
    description: "Shampoos and hair-care preparations.",
    keywords: ["shampoo", "hair care", "conditioner", "hair wash"],
    chapter: "33",
    section: "VI",
    dutyRatePlaceholder: "0% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "ingredient/INCI list"],
    restrictionNotes: ["EU/UK cosmetic notification required."],
    riskLevel: "high",
  },

  // ---------------------------------------------------------- Food products
  {
    code: "0901.21",
    jurisdiction: "GLOBAL",
    title: "Roasted coffee, not decaffeinated",
    description: "Coffee, roasted, not decaffeinated.",
    keywords: ["coffee", "roasted coffee", "coffee beans", "ground coffee"],
    chapter: "09",
    section: "II",
    dutyRatePlaceholder: "~7.5% (EU MFN, placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "certificate of origin",
      "phytosanitary / health certificate",
    ],
    restrictionNotes: [
      "Foodstuff — EU/UK food safety, labelling and import controls apply.",
      "Possible sanitary/phytosanitary checks at the border.",
    ],
    riskLevel: "high",
  },
  {
    code: "1806.32",
    jurisdiction: "GLOBAL",
    title: "Chocolate in blocks/bars, not filled",
    description: "Chocolate and other cocoa preparations in blocks, slabs or bars, not filled.",
    keywords: ["chocolate", "cocoa", "candy bar", "confectionery", "chocolate bar"],
    chapter: "18",
    section: "IV",
    dutyRatePlaceholder: "~8.3% + agri component (EU, placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "health certificate",
      "ingredient list",
    ],
    restrictionNotes: ["Foodstuff — food safety and labelling controls apply."],
    riskLevel: "high",
  },
  {
    code: "2009.89",
    jurisdiction: "GLOBAL",
    title: "Fruit/vegetable juices (other), not fermented",
    description: "Single fruit or vegetable juices, unfermented and not containing added spirit.",
    keywords: ["juice", "fruit juice", "vegetable juice", "beverage", "drink"],
    chapter: "20",
    section: "IV",
    dutyRatePlaceholder: "variable + agri component (EU, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "health certificate"],
    restrictionNotes: ["Foodstuff — sanitary controls and labelling apply."],
    riskLevel: "high",
  },
  {
    code: "2106.90",
    jurisdiction: "GLOBAL",
    title: "Food preparations not elsewhere specified (incl. supplements)",
    description: "Food preparations n.e.s., including food/dietary supplements.",
    keywords: ["supplement", "food supplement", "protein powder", "vitamins", "nutrition", "food preparation"],
    chapter: "21",
    section: "IV",
    dutyRatePlaceholder: "variable (EU, placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "ingredient/composition breakdown",
      "health certificate",
    ],
    restrictionNotes: [
      "Food supplements — novel-food and health-claim rules may apply (EU/UK).",
      "May require notification to national authorities.",
    ],
    riskLevel: "high",
  },

  // ---------------------------------------------------------- Plastic goods
  {
    code: "3924.10",
    jurisdiction: "GLOBAL",
    title: "Tableware and kitchenware of plastics",
    description: "Plastic tableware, kitchenware and household articles.",
    keywords: ["plastic", "tableware", "kitchenware", "container", "plastic cup", "plastic plate", "household"],
    chapter: "39",
    section: "VII",
    dutyRatePlaceholder: "~6.5% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "food-contact declaration"],
    restrictionNotes: ["Food-contact plastics must meet EU 10/2011 / FDA migration requirements."],
    riskLevel: "medium",
  },
  {
    code: "3926.90",
    jurisdiction: "GLOBAL",
    title: "Other articles of plastics",
    description: "Other articles of plastics not elsewhere specified.",
    keywords: ["plastic", "plastic article", "plastic part", "plastic accessory", "moulded plastic"],
    chapter: "39",
    section: "VII",
    dutyRatePlaceholder: "~6.5% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: [],
    riskLevel: "low",
  },
  {
    code: "3923.30",
    jurisdiction: "GLOBAL",
    title: "Plastic bottles, flasks and similar articles",
    description: "Carboys, bottles, flasks and similar articles for the conveyance/packing of goods, of plastics.",
    keywords: ["plastic bottle", "bottle", "flask", "packaging", "container", "pet bottle"],
    chapter: "39",
    section: "VII",
    dutyRatePlaceholder: "~6.5% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: [],
    riskLevel: "low",
  },

  // ------------------------------------------------------------ Metal goods
  {
    code: "7323.93",
    jurisdiction: "GLOBAL",
    title: "Stainless steel kitchen/household articles",
    description: "Table, kitchen or other household articles of stainless steel.",
    keywords: ["stainless steel", "kitchenware", "cookware", "pot", "pan", "utensil", "metal household"],
    chapter: "73",
    section: "XV",
    dutyRatePlaceholder: "~3.2% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "mill test certificate"],
    restrictionNotes: ["Steel products may be subject to safeguard quotas/anti-dumping in EU/US."],
    riskLevel: "medium",
  },
  {
    code: "7616.99",
    jurisdiction: "GLOBAL",
    title: "Other articles of aluminium",
    description: "Other articles of aluminium not elsewhere specified.",
    keywords: ["aluminium", "aluminum", "metal part", "aluminium article", "alloy"],
    chapter: "76",
    section: "XV",
    dutyRatePlaceholder: "~6% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: ["Aluminium may be subject to anti-dumping measures in EU/US."],
    riskLevel: "medium",
  },
  {
    code: "8302.41",
    jurisdiction: "GLOBAL",
    title: "Base metal mountings/fittings for buildings",
    description: "Base metal mountings, fittings and similar articles suitable for buildings.",
    keywords: ["hinge", "fitting", "bracket", "mounting", "hardware", "metal fitting", "handle"],
    chapter: "83",
    section: "XV",
    dutyRatePlaceholder: "~2.7% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: [],
    riskLevel: "low",
  },
  {
    code: "8211.92",
    jurisdiction: "GLOBAL",
    title: "Knives with fixed blades",
    description: "Knives with cutting blades, fixed, other than table knives.",
    keywords: ["knife", "blade", "cutlery", "fixed blade", "hunting knife", "utility knife"],
    chapter: "82",
    section: "XV",
    dutyRatePlaceholder: "~8.5% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: ["Certain knives (flick/automatic) are prohibited/restricted in UK/EU."],
    riskLevel: "medium",
  },

  // -------------------------------------------------------------- Furniture
  {
    code: "9403.60",
    jurisdiction: "GLOBAL",
    title: "Wooden furniture (other)",
    description: "Other wooden furniture not elsewhere specified.",
    keywords: ["furniture", "wooden furniture", "table", "cabinet", "shelf", "wood", "dresser"],
    chapter: "94",
    section: "XX",
    dutyRatePlaceholder: "0% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "ISPM-15 (wood packaging)"],
    restrictionNotes: ["EUTR/UKTR timber due-diligence may apply; ISPM-15 for solid-wood packaging."],
    riskLevel: "medium",
  },
  {
    code: "9401.61",
    jurisdiction: "GLOBAL",
    title: "Upholstered seats with wooden frames",
    description: "Seats with wooden frames, upholstered.",
    keywords: ["chair", "seat", "sofa", "armchair", "upholstered", "couch", "furniture"],
    chapter: "94",
    section: "XX",
    dutyRatePlaceholder: "0% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: ["Upholstery fire-safety regulations apply in the UK."],
    riskLevel: "medium",
  },
  {
    code: "9404.21",
    jurisdiction: "GLOBAL",
    title: "Mattresses of cellular rubber or plastics",
    description: "Mattresses of cellular rubber or plastics, whether or not covered.",
    keywords: ["mattress", "foam mattress", "memory foam", "bedding"],
    chapter: "94",
    section: "XX",
    dutyRatePlaceholder: "~3.7% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: ["Fire-safety regulations apply in the UK."],
    riskLevel: "medium",
  },

  // ----------------------------------------------------------- Books / paper
  {
    code: "4901.99",
    jurisdiction: "GLOBAL",
    title: "Printed books, brochures and similar printed matter",
    description: "Printed books, brochures, leaflets and similar printed matter.",
    keywords: ["book", "printed book", "brochure", "paperback", "hardcover", "literature"],
    chapter: "49",
    section: "X",
    dutyRatePlaceholder: "0% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: [],
    riskLevel: "low",
  },
  {
    code: "4820.10",
    jurisdiction: "GLOBAL",
    title: "Notebooks, diaries and similar paper stationery",
    description: "Registers, notebooks, diaries and similar articles of paper or paperboard.",
    keywords: ["notebook", "diary", "stationery", "journal", "paper", "writing pad"],
    chapter: "48",
    section: "X",
    dutyRatePlaceholder: "0% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: [],
    riskLevel: "low",
  },
  {
    code: "4819.20",
    jurisdiction: "GLOBAL",
    title: "Folding cartons and boxes of paper/paperboard",
    description: "Folding cartons, boxes and cases of non-corrugated paper or paperboard.",
    keywords: ["box", "carton", "packaging", "paperboard", "cardboard", "folding box"],
    chapter: "48",
    section: "X",
    dutyRatePlaceholder: "0% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: [],
    riskLevel: "low",
  },

  // ------------------------------------------------------------------- Toys
  {
    code: "9503.00",
    jurisdiction: "GLOBAL",
    title: "Toys, tricycles, dolls and puzzles",
    description: "Tricycles, scooters, dolls, puzzles and other toys; reduced-scale models.",
    keywords: ["toy", "doll", "puzzle", "figurine", "toy car", "play set", "children toy", "stuffed toy"],
    chapter: "95",
    section: "XX",
    dutyRatePlaceholder: "0% (EU MFN, placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "declaration of conformity (toy safety)",
    ],
    restrictionNotes: [
      "EU Toy Safety Directive 2009/48/EC / UKCA — CE/UKCA marking and EN71 testing required.",
      "Toys with electronics/batteries carry additional obligations.",
    ],
    riskLevel: "medium",
  },
  {
    code: "9503.00.75",
    jurisdiction: "GLOBAL",
    title: "Electronic toys with batteries",
    description: "Electric/electronic toys incorporating motors or batteries.",
    keywords: ["electronic toy", "rc car", "remote control toy", "battery toy", "drone toy", "robot toy"],
    chapter: "95",
    section: "XX",
    dutyRatePlaceholder: "0% (EU MFN, placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "declaration of conformity (toy + EMC/RED)",
    ],
    restrictionNotes: [
      "Toy safety + EMC + (if wireless) radio conformity required.",
      "Battery transport rules apply.",
    ],
    riskLevel: "high",
  },

  // -------------------------------------------------------------- Machinery
  {
    code: "8414.51",
    jurisdiction: "GLOBAL",
    title: "Table/floor/wall fans, ≤125W",
    description: "Table, floor, wall, window, ceiling or roof fans with a self-contained electric motor ≤125W.",
    keywords: ["fan", "electric fan", "cooling fan", "desk fan", "ventilation"],
    chapter: "84",
    section: "XVI",
    dutyRatePlaceholder: "~2.3% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "declaration of conformity"],
    restrictionNotes: ["LVD/EMC conformity (CE/UKCA) applies."],
    riskLevel: "medium",
  },
  {
    code: "8467.21",
    jurisdiction: "GLOBAL",
    title: "Hand-held electric drills",
    description: "Tools for working in the hand, with self-contained electric motor — drills of all kinds.",
    keywords: ["drill", "power tool", "electric drill", "cordless drill", "hand tool"],
    chapter: "84",
    section: "XVI",
    dutyRatePlaceholder: "~1.7% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "declaration of conformity"],
    restrictionNotes: [
      "Machinery Directive + LVD/EMC conformity applies.",
      "Cordless models contain lithium batteries — transport rules apply.",
    ],
    riskLevel: "medium",
  },
  {
    code: "8479.89",
    jurisdiction: "GLOBAL",
    title: "Machines with individual functions, n.e.s.",
    description: "Machines and mechanical appliances having individual functions, not specified elsewhere.",
    keywords: ["machine", "machinery", "mechanical appliance", "industrial machine", "equipment"],
    chapter: "84",
    section: "XVI",
    dutyRatePlaceholder: "~1.7% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "declaration of conformity"],
    restrictionNotes: ["Machinery Directive conformity may apply."],
    riskLevel: "medium",
  },
  {
    code: "8413.70",
    jurisdiction: "GLOBAL",
    title: "Centrifugal pumps (other)",
    description: "Other centrifugal pumps for liquids.",
    keywords: ["pump", "water pump", "centrifugal pump", "liquid pump"],
    chapter: "84",
    section: "XVI",
    dutyRatePlaceholder: "~1.7% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: [],
    riskLevel: "low",
  },

  // ----------------------------------------------------------- Home / misc
  {
    code: "7013.49",
    jurisdiction: "GLOBAL",
    title: "Glassware for table or kitchen (other)",
    description: "Glassware of a kind used for table or kitchen purposes (other than glass-ceramics).",
    keywords: ["glass", "glassware", "drinking glass", "tumbler", "glass bowl", "kitchen glass"],
    chapter: "70",
    section: "XIII",
    dutyRatePlaceholder: "~11% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "food-contact declaration"],
    restrictionNotes: ["Food-contact materials must meet migration requirements."],
    riskLevel: "low",
  },
  {
    code: "6913.90",
    jurisdiction: "GLOBAL",
    title: "Ceramic ornamental articles (other)",
    description: "Statuettes and other ornamental ceramic articles.",
    keywords: ["ceramic", "ornament", "figurine", "pottery", "decorative", "porcelain ornament"],
    chapter: "69",
    section: "XIII",
    dutyRatePlaceholder: "~6% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: [],
    riskLevel: "low",
  },
  {
    code: "9405.11",
    jurisdiction: "GLOBAL",
    title: "Electric ceiling/wall lighting fittings (LED)",
    description: "Electric ceiling or wall lighting fittings designed for LED light sources.",
    keywords: ["lamp", "light", "led", "lighting", "luminaire", "light fitting", "ceiling light"],
    chapter: "94",
    section: "XX",
    dutyRatePlaceholder: "~3.7% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "declaration of conformity"],
    restrictionNotes: ["LVD/EMC/RoHS conformity (CE/UKCA) applies; WEEE obligations."],
    riskLevel: "medium",
  },
  {
    code: "9102.11",
    jurisdiction: "GLOBAL",
    title: "Wrist-watches, electrically operated, mechanical display",
    description: "Wrist-watches, electrically operated, with mechanical display only.",
    keywords: ["watch", "wristwatch", "timepiece", "quartz watch", "wrist watch"],
    chapter: "91",
    section: "XVIII",
    dutyRatePlaceholder: "~4.5% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: ["Contains a battery; smartwatches re-classify to ch.85 (radio conformity)."],
    riskLevel: "low",
  },
  {
    code: "7117.19",
    jurisdiction: "GLOBAL",
    title: "Imitation jewellery of base metal",
    description: "Imitation jewellery of base metal, whether or not plated with precious metal.",
    keywords: ["jewellery", "jewelry", "imitation jewellery", "costume jewelry", "necklace", "bracelet", "earrings"],
    chapter: "71",
    section: "XIV",
    dutyRatePlaceholder: "~4% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: ["Nickel-release limits apply for skin-contact items (EU/UK REACH)."],
    riskLevel: "medium",
  },

  // ------------------------------------------------- Medical-adjacent (HIGH)
  {
    code: "9018.39",
    jurisdiction: "GLOBAL",
    title: "Medical instruments — needles, catheters, cannulae (other)",
    description: "Syringes, needles, catheters, cannulae and similar medical instruments.",
    keywords: ["medical", "syringe", "needle", "catheter", "cannula", "medical instrument", "medical device"],
    chapter: "90",
    section: "XVIII",
    dutyRatePlaceholder: "0% (EU MFN, placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "declaration of conformity (MDR)",
      "CE/UKCA certificate",
    ],
    restrictionNotes: [
      "Medical device — EU MDR 2017/745 / UK MDR registration and conformity required.",
      "Importer/Authorised Representative obligations apply.",
    ],
    riskLevel: "high",
  },
  {
    code: "9021.10",
    jurisdiction: "GLOBAL",
    title: "Orthopaedic or fracture appliances",
    description: "Orthopaedic appliances, splints and other fracture appliances.",
    keywords: ["orthopaedic", "orthopedic", "splint", "brace", "support", "medical appliance"],
    chapter: "90",
    section: "XVIII",
    dutyRatePlaceholder: "0% (EU MFN, placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "declaration of conformity (MDR)",
    ],
    restrictionNotes: ["Medical device registration/conformity required (EU MDR / UK MDR)."],
    riskLevel: "high",
  },
  {
    code: "3005.90",
    jurisdiction: "GLOBAL",
    title: "Wadding, gauze, bandages and dressings",
    description: "Wadding, gauze, bandages and similar articles impregnated/coated for medical use.",
    keywords: ["bandage", "gauze", "dressing", "plaster", "wound care", "first aid", "medical dressing"],
    chapter: "30",
    section: "VI",
    dutyRatePlaceholder: "0% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "declaration of conformity (MDR)"],
    restrictionNotes: ["Medical device classification may apply — conformity/registration required."],
    riskLevel: "high",
  },
  {
    code: "3004.90",
    jurisdiction: "GLOBAL",
    title: "Medicaments, packaged for retail (other)",
    description: "Medicaments consisting of mixed or unmixed products for therapeutic use, retail packaged.",
    keywords: ["medicine", "medicament", "pharmaceutical", "drug", "tablet", "capsule", "pharma"],
    chapter: "30",
    section: "VI",
    dutyRatePlaceholder: "0% (EU MFN, placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "marketing authorisation",
      "import licence",
      "GMP certificate",
    ],
    restrictionNotes: [
      "Pharmaceuticals — strict licensing (EMA/MHRA/FDA). Import licence and authorisation required.",
      "Controlled substances may be prohibited without special permits.",
    ],
    riskLevel: "high",
  },

  // ----------------------------------------------------- Chemicals (HIGH)
  {
    code: "3402.20",
    jurisdiction: "GLOBAL",
    title: "Surface-active preparations / detergents, retail",
    description: "Washing and cleaning preparations put up for retail sale.",
    keywords: ["detergent", "cleaning", "surfactant", "cleaner", "soap solution", "washing"],
    chapter: "34",
    section: "VI",
    dutyRatePlaceholder: "~4% (EU MFN, placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "safety data sheet (SDS)",
    ],
    restrictionNotes: [
      "Chemical mixture — EU/UK REACH and CLP labelling apply.",
      "Detergent Regulation (EC) 648/2004 applies in the EU.",
    ],
    riskLevel: "high",
  },
  {
    code: "3208.90",
    jurisdiction: "GLOBAL",
    title: "Paints and varnishes (synthetic polymer, non-aqueous)",
    description: "Paints and varnishes based on synthetic polymers, in a non-aqueous medium.",
    keywords: ["paint", "varnish", "coating", "lacquer", "solvent paint", "chemical coating"],
    chapter: "32",
    section: "VI",
    dutyRatePlaceholder: "~6.5% (EU MFN, placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "safety data sheet (SDS)",
      "dangerous goods declaration",
    ],
    restrictionNotes: [
      "Often flammable (Class 3 dangerous goods) — transport rules apply.",
      "REACH/CLP and VOC limits apply.",
    ],
    riskLevel: "high",
  },
  {
    code: "2815.12",
    jurisdiction: "GLOBAL",
    title: "Sodium hydroxide in aqueous solution",
    description: "Sodium hydroxide (caustic soda) in aqueous solution (soda lye).",
    keywords: ["sodium hydroxide", "caustic soda", "lye", "chemical", "industrial chemical", "corrosive"],
    chapter: "28",
    section: "VI",
    dutyRatePlaceholder: "~5.5% (EU MFN, placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "safety data sheet (SDS)",
      "dangerous goods declaration",
    ],
    restrictionNotes: [
      "Corrosive (Class 8 dangerous goods) — transport rules apply.",
      "REACH registration and CLP labelling required.",
    ],
    riskLevel: "high",
  },
  {
    code: "3824.99",
    jurisdiction: "GLOBAL",
    title: "Chemical products/preparations, n.e.s.",
    description: "Chemical products and preparations of the chemical industry not elsewhere specified.",
    keywords: ["chemical", "chemical preparation", "industrial chemical", "compound", "mixture", "reagent"],
    chapter: "38",
    section: "VI",
    dutyRatePlaceholder: "~6.5% (EU MFN, placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "safety data sheet (SDS)",
    ],
    restrictionNotes: [
      "REACH/CLP obligations; some preparations may be dual-use or restricted.",
      "Confirm CAS numbers and dangerous-goods classification.",
    ],
    riskLevel: "high",
  },

  // ----------------------------------------------- Controlled / dual-use (HIGH)
  {
    code: "9305.99",
    jurisdiction: "GLOBAL",
    title: "Parts and accessories of arms (other)",
    description: "Parts and accessories of articles of headings 93.01–93.04 (arms).",
    keywords: ["weapon part", "firearm part", "arms", "gun part", "ammunition part"],
    chapter: "93",
    section: "XIX",
    dutyRatePlaceholder: "controlled (placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "export/import licence",
      "end-use certificate",
    ],
    restrictionNotes: [
      "Controlled goods — arms export/import licensing required; may be prohibited.",
      "Strict end-user controls apply.",
    ],
    riskLevel: "high",
  },
  {
    code: "8526.10",
    jurisdiction: "GLOBAL",
    title: "Radar apparatus",
    description: "Radar apparatus (may be dual-use depending on specification).",
    keywords: ["radar", "radar apparatus", "detection", "dual-use", "sensor"],
    chapter: "85",
    section: "XVI",
    dutyRatePlaceholder: "controlled / placeholder",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "dual-use declaration",
      "export licence (if controlled)",
    ],
    restrictionNotes: [
      "Potential dual-use item (EU Reg 2021/821) — screening and possible licensing required.",
    ],
    riskLevel: "high",
  },

  // ------------------------------------------- Alcohol / tobacco (HIGH, excise)
  {
    code: "2204.21",
    jurisdiction: "GLOBAL",
    title: "Wine in containers ≤2 litres",
    description: "Wine of fresh grapes in containers holding 2 litres or less.",
    keywords: ["wine", "alcohol", "red wine", "white wine", "bottle of wine", "beverage alcohol"],
    chapter: "22",
    section: "IV",
    dutyRatePlaceholder: "duty + excise (placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "VI-1 / certificate of origin",
      "excise documentation",
    ],
    restrictionNotes: [
      "Excise goods — excise duty, licensing and movement controls apply.",
      "Age-restricted; labelling rules apply.",
    ],
    riskLevel: "high",
  },
  {
    code: "2402.20",
    jurisdiction: "GLOBAL",
    title: "Cigarettes containing tobacco",
    description: "Cigarettes containing tobacco.",
    keywords: ["cigarettes", "tobacco", "cigarette", "smoking"],
    chapter: "24",
    section: "IV",
    dutyRatePlaceholder: "duty + excise (placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "excise documentation",
      "import licence",
    ],
    restrictionNotes: [
      "Excise goods — heavy excise, track-and-trace, health-warning and licensing rules.",
      "Strictly age-restricted; may require special authorisation.",
    ],
    riskLevel: "high",
  },

  // ----------------------------------------------- Animal / plant (HIGH, SPS)
  {
    code: "0307.43",
    jurisdiction: "GLOBAL",
    title: "Cuttlefish and squid, frozen",
    description: "Frozen cuttlefish and squid (molluscs).",
    keywords: ["seafood", "squid", "cuttlefish", "frozen fish", "mollusc", "animal product"],
    chapter: "03",
    section: "I",
    dutyRatePlaceholder: "variable (EU, placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "health certificate (veterinary)",
      "catch certificate",
    ],
    restrictionNotes: [
      "Animal product — SPS/veterinary controls; BIP/BCP checks required.",
      "IUU catch certificate required for EU/UK import.",
    ],
    riskLevel: "high",
  },
  {
    code: "0603.11",
    jurisdiction: "GLOBAL",
    title: "Fresh cut roses",
    description: "Fresh cut roses, suitable for bouquets or ornamental purposes.",
    keywords: ["flowers", "roses", "cut flowers", "plant", "fresh flowers", "bouquet"],
    chapter: "06",
    section: "II",
    dutyRatePlaceholder: "variable (EU, placeholder)",
    requiredDocuments: [
      "commercial invoice",
      "packing list",
      "phytosanitary certificate",
    ],
    restrictionNotes: [
      "Plant product — phytosanitary certificate and import checks required.",
      "Possible CITES controls for protected species.",
    ],
    riskLevel: "high",
  },

  // --------------------------------------------------------- Sporting goods
  {
    code: "8712.00",
    jurisdiction: "GLOBAL",
    title: "Bicycles and other cycles, not motorized",
    description:
      "Two-wheeled and other non-motorized bicycles, including road, racing, gravel and city bicycles.",
    keywords: [
      "bicycle", "bike", "cycle", "road bike", "racing bike", "gravel bike",
      "cycling", "tarmac", "specialized", "trek", "carbon fiber bicycle",
      "road racing bicycle",
    ],
    chapter: "87",
    section: "XVII",
    dutyRatePlaceholder: "~14% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list", "certificate of origin"],
    restrictionNotes: [
      "Anti-dumping/countervailing duties may apply depending on country of origin (e.g., historically for China-origin bicycles) — verify current trade remedy measures.",
    ],
    riskLevel: "medium",
  },
  {
    code: "8714.91",
    jurisdiction: "GLOBAL",
    title: "Bicycle frames, forks, and parts thereof",
    description:
      "Frames and forks for bicycles and other cycles, and parts of frames/forks (e.g. carbon-fiber framesets sold separately from a complete bicycle).",
    keywords: [
      "bicycle frame", "frameset", "fork", "carbon frame", "bike frame",
      "frame and fork",
    ],
    chapter: "87",
    section: "XVII",
    dutyRatePlaceholder: "~4.7% (EU MFN, placeholder)",
    requiredDocuments: ["commercial invoice", "packing list"],
    restrictionNotes: [],
    riskLevel: "low",
  },
];

/** Quick lookup by code. */
export const SEED_BY_CODE: Map<string, TariffCode> = new Map(
  SEED_TARIFF_CODES.map((c) => [c.code, c]),
);
